### ISSUE TITLE
Fails in Visual Studio Code

### ISSUE THREAD

**Issue by jvonehr** [awesomeeng/awesome-log#27]
Just found AwesomeLog today & installed it. Nice piece of work, and very nice code, and it seems way cleaner than the other packages I've looked at. Unfortunately, it fails to log anything when I run my code from VisualStudioCode. Buffers the formatted lines during init, then when it finally calls print.call(...) to emit them, that print function is empty.

Testing with your simple test "ExampleUsage.js". Tried it on Mac & Ubuntu with same result. However, it works fine when the test program is run from a command line on either platform, so has to be something VSC is doing. I've tried to follow what's going on, but not yet skilled enough JS programmer to follow the 'interesting' things you're doing.

Update: just tried winston logger, with exactly the same result in VSC vs. command line. Seems like a VSC issue...

**Comment by arei** [comment]
I have seen this before and IIRC you need to add `"outputCapture": "std"` to your `launch.json` file for the executing section. If `std` doesnt work, try `console`. 

Please let me know if this solves your problem.

**Comment by jvonehr** [comment]
A bit tricky, but that was the answer!

There doesn’t seem to be a ‘launch.json’ file in current VSC release, so it needs to be created in VSC:

1. Click the debug icon on the icons at left 
2. It puts up a panel on the left with the option to create a “launch.json” file
3. Click that, and specify “node.js” environment to open it
4. Add the “outputCapture”: “std” field inside ‘configurations’

All is well now. Look forward to exploring your nice piece of work. Thanks for this package.

Regards,

Jim
----------------

**Comment by arei** [comment]
Glad it work, glad you like the package. Tell your friends! And check out AwesomeServer if you like this one.
